###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Falin, CS165
# Author:
#     Jacob Alldredge
# Summary:
#     This program will function to receive various information
#     about customers and items that they wish to purchase. It
#     will serve to calculate their costs and present the total
#     costs and item information in a pleasent format 
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

