#################################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Falin, CS165
# Author:
#     Jacob Alldredge
# Summary:
#     The purpose of this program is to receive information on
#     a product and present it in a form requested by the user.
#     Program will calculate shipping cost and tax when required.
#################################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

